version: 1.18.2-develop+{build}
branches:
  only:
  - master
  - develop
  - /^release/
  - /^appveyor/
  - /^build-ci/
image:
- Visual Studio 2017
- Visual Studio 2015
build_script:
- cmd: >-
    if "Visual Studio 2017"=="%APPVEYOR_BUILD_WORKER_IMAGE%" call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
      if "Visual Studio 2015"=="%APPVEYOR_BUILD_WORKER_IMAGE%" call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
      if "Visual Studio 2015"=="%APPVEYOR_BUILD_WORKER_IMAGE%" call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
      cd..
      git clone https://github.com/libtom/libtommath.git --branch=master
      cd libtommath
      nmake -f makefile.msvc
      cd..
      cd libtomcrypt
      nmake -f makefile.msvc all
test_script:
- cmd: test.exe
